
services:
  service-user:
    build: 
      context: ./service-user
      dockerfile: Dockerfile
    container_name: service-user
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/userdb
      - PORT=5000
    depends_on:
      - mongodb
      - rabbitmq 
    networks:
      - network-dapr
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=service-user"
      - "dapr.io/app-port=5000"

  dapr_user:
    container_name: dapr_user
    image: "daprio/daprd:latest"
    command: ["./daprd", "-app-id", "service-user", "-app-port", "5000","-app-protocol", "http","-dapr-http-port", "3500"]
    network_mode: "service:service-user"
    depends_on:
      - "service-user"
  
  service-news:
    build:
      context: ./service-news
      dockerfile: Dockerfile
    container_name: service-news
    ports:
      - "5001:5001"
    environment:
      - NEWS_API_KEY=b684b5f306a242509e3524c91089b088 # המפתח שלך לשירות NewsAPI
    depends_on:
      - rabbitmq 
    networks:
      - network-dapr 
   
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=service-news"
      - "dapr.io/app-port=5001"
    
  
  dapr_news:
    container_name: dapr_news
    image: "daprio/daprd:latest"
    command: ["./daprd", "-app-id", "service-news", "-app-port", "5001","-app-protocol", "http","-dapr-http-port", "3500"]
    depends_on:
      - service-news
    network_mode: "service:service-news" 

  service-notification:
    build:
      context: ./service-notification
      dockerfile: Dockerfile
    container_name: service-notification
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq 
    networks:
      - network-dapr 
   
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=service-notification"
      - "dapr.io/app-port=5002"
    
  
  dapr_notification:
    container_name: dapr_notification
    image: "daprio/daprd:latest"
    command: ["./daprd", "-app-id", "service-notification", "-app-port", "5002","-app-protocol", "http","-dapr-http-port", "3500"]
    depends_on:
      - service-notification
    network_mode: "service:service-notification"
  
  mongodb:
    image: mongo 
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - network-dapr
    
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "15672:15672"  
      - "5672:5672" 
    networks:
      - network-dapr     
  
  
 
    
networks:
  network-dapr:
    driver: bridge

volumes:
  mongo-data:
